server:
  port: 8202

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/groupbuying-sys?characterEncoding=utf-8&useSSL=false
    username: root
    password: 121314

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8